tools:
  - name: "backstage_mcp_tools"
    url: "https://rhdh-mcp-proxy-apicast-production.apps.rosa.redhat-ai-dev.m6no.p3.openshiftapps.com:443/api/mcp-actions/v1"
    transport: "streamable-http"
    bearerTokenEnvVarName: "MCP_TOKEN"

